# Generated by Django 2.1.7 on 2019-03-14 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UM_sent_messages',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(max_length=16)),
                ('message_body_plaintext', models.TextField()),
                ('created_at', models.DateTimeField(blank=True)),
                ('UM_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UM_session',
            fields=[
                ('sesssion_id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('UM_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
